In [16]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# Implement Mean Absolute Error

In [3]:
def mae(a,b):
    t=0
    for i,j in zip(a,b):
        t+=abs(i-j)
    print("Total Error: ",t)
    mae = t/len(a)
    print("MAE: ",mae)
    return mae

In [4]:
mae(y_predicted,y_true)

Total Error:  2.5
MAE:  0.5


0.5

In [12]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [13]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [14]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [15]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

# MSE

In [18]:
def mse(a,b):
    t=0
    for i,j in zip(a,b):
        t+=(i-j)**2
    print("Total Error: ",t)
    mae = t/len(a)
    print("MAE: ",mae)
    return mae

In [19]:
mse(y_predicted,y_true)

Total Error:  1.83
MAE:  0.366


0.366

In [33]:
def mse_np(a,b):
    return np.mean(np.square(a-b))

In [34]:
mse_np(y_predicted,y_true)

0.366

# Implement Log Loss or Binary Cross Entropy

In [22]:
epsilon = 1e-15
np.log([1e-15])

array([-34.53877639])

In [23]:
y_predicted

array([1, 1, 0, 0, 1])

In [24]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [26]:
1-epsilon

0.999999999999999

In [27]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [28]:
y_predicted_new = np.array(y_predicted_new)

In [29]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [30]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [31]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [32]:
log_loss(y_true, y_predicted)

17.2696280766844